name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        key: ${{secrets.SECRETS}}
        envs: GITHUB_SHA
        script: |
          docker pull reljacer/action-demo:${GITHUB_SHA::7}
          docker tag reljacer/action-demo:${GITHUB_SHA::7} action-demo
          docker stop server
          docker run -d --rm --name server -p 8080:8000 action-demo
