name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.USERNAME}} -p ${{ secrets.PASSWORD }}
        docker build -t action-demo .
        docker tag spring-cicd ${{secret.USERNAME}}/action-demo:${GITHUB_SHA::7}
        docker push ${{secrets.USERNAME}}/action-demo:${GITHUB_SHA::7}
